name = "System Power Controls"
description = "Control system power (shutdown, restart, sleep, etc)"
repository = "https://github.com/blorbb/covey-plugins"
authors = ["blorbb"]

[[commands]]
id = "activate"
title = "Activate"
default-hotkeys = ["Enter"]
