name = "Text edit"
description = "Miscellaneous text editing utilities"
repository = "https://github.com/blorbb/covey-plugins"
authors = ["blorbb"]

[[commands]]
id = "activate"
title = "Copy"
default-hotkeys = ["Enter"]

[[commands]]
id = "complete"
title = "Complete"
default-hotkeys = ["Enter", "Tab"]
