[package]
name = "qalc"
version = "0.1.0"
edition.workspace = true

[dependencies]
covey-plugin.workspace = true
tokio = { version = "1.41.1", features = ["process", "fs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
