name = "Qalculate"
description = "Calculate using qalc"
repository = "https://github.com/blorbb/covey-plugins"
authors = ["blorbb"]

[[commands]]
id = "copy"
title = "Copy result"
default-hotkeys = [{ key = "enter" }]

[[commands]]
id = "copy-equation"
title = "Copy equation"
default-hotkeys = [{ key = "enter", alt = true }]

[[commands]]
id = "complete"
title = "Insert result"
description = "Replace the current input with the result"
default-hotkeys = [{ key = "tab" }]
