name = "Qalculate"
description = "Calculate using qalc"
repository = "https://github.com/blorbb/covey-plugins"
authors = ["blorbb"]

[[commands]]
id = "copy"
title = "Copy result"
default-hotkeys = [{ key = "enter" }]

[[commands]]
id = "copy-equation"
title = "Copy equation"
default-hotkeys = [{ key = "enter", alt = true }]

[[commands]]
id = "complete"
title = "Insert result"
description = "Replace the current input with the result"
default-hotkeys = [{ key = "tab" }]

# commands for history items
[[commands]]
id = "append-history-result"
title = "Append history result"
description = "Add the result of the selected history item to the end of the current equation"
default-hotkeys = [{ key = "enter" }, { key = "tab" }]

[[commands]]
id = "insert-history-query"
title = "Insert history query"
description = "Set the input to the query of the selected history item"
default-hotkeys = [{ key = "enter", alt = true }]
